source $HOME/.config/nvim/general_settings.vim
source $HOME/.config/nvim/leader_no_plugins.vim
source $HOME/.config/nvim/dracula.vim

set cursorline

" Coursor appearance -- depends on mode
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

" Make coursor shape immidiate
set timeoutlen=1000
set ttimeoutlen=1

" Statusline
set laststatus=2
set statusline=
set statusline=%t\ %M\ %=\ %y\ %{&fileencoding?&fileencoding:&encoding}\ \[%{&fileformat}\]\ %l/%L:\ %v

" No welcome message
set shortmess+=I

" Żeby terminal był przezroczysty
hi Normal guibg=NONE ctermbg=NONE

" Żeby linia była zaznaczona bez koloru
hi CursorLine   cterm=NONE ctermbg=NONE ctermfg=NONE
