" Plugins
call plug#begin()
    Plug 'vimwiki/vimwiki'
call plug#end()

" General
set nocompatible

set ignorecase smartcase incsearch complete+=s showmatch hlsearch
set path+=**

set expandtab softtabstop=4 shiftwidth=4 tabstop=4
set wrap linebreak smartindent tw=74
set backspace=indent,eol,start
set wildmenu

set display+=lastline scrolloff=10 nojoinspaces
set splitbelow splitright

set clipboard^=unnamed,unnamedplus
set noswapfile nobackup

set fo=croql
autocmd BufRead,BufNewFile   *.txt set fo=tawc nosmartindent autoindent
autocmd BufRead,BufNewFile   *.md set fo=tawc nosmartindent autoindent
autocmd BufRead,BufNewFile   *.wiki set fo=tawc nosmartindent autoindent

syntax on
set omnifunc=syntaxcomplete#Complete

set rnu nu
set showcmd

set timeoutlen=1000 ttimeoutlen=1

set shortmess+=I

set colorcolumn=76
set cursorline

" Colorscheme
colorscheme default

hi IncSearch        ctermbg=0            ctermfg=253
hi Search           ctermbg=130          ctermfg=236
hi Visual           cterm=reverse        ctermbg=NONE
hi ColorColumn      ctermbg=237
hi CursorLine       ctermbg=NONE         cterm=NONE
hi SpellBad         ctermbg=NONE         ctermbg=239
hi CursorLineNr     cterm=bold
hi Title            ctermfg=255          cterm=bold
hi vimwikiItalic    ctermfg=228          cterm=italic
hi htmlItalic       ctermfg=228          cterm=italic
hi markdownItalic   ctermfg=228          cterm=italic
hi vimwikiBold      ctermfg=228          cterm=bold
hi htmlBold         ctermfg=228          cterm=bold
hi markdownBold     ctermfg=228          cterm=bold
hi Identifier       ctermfg=109
hi Underlined       ctermfg=109          cterm=NONE
hi ModeMsg          ctermbg=NONE         ctermfg=208
hi MatchParen       ctermbg=NONE         ctermbg=241
hi Todo             ctermbg=NONE         ctermfg=166    cterm=bold

hi statusline cterm=bold ctermfg=250 ctermbg=none
set laststatus=2
set statusline=\|%*\ %t\ %M\ \ %*%=\ %p%%\ \ %l:\ %2v\ \|%* 

" Normal mode
nnoremap j gj
nnoremap k gk
nnoremap 0 g0
nnoremap $ g$
nnoremap <C-k> k
nnoremap <C-j> j
nnoremap <C-h> h
nnoremap <C-l> l

nnoremap Q gq

nnoremap Y y$
nnoremap n nzzzv
nnoremap N Nzzzv

" Insert mode
inoremap <C-j> <CR>- 

inoremap . .<c-g>u
inoremap - -<c-g>u
inoremap ! !<c-g>u
inoremap ? ?<c-g>u

" Console mode
cnoremap W w
cnoremap Q q

" Visual mode
vmap < <gv
vmap > >gv

vnoremap j gj
vnoremap k gk
vnoremap <C-k> k
vnoremap <C-j> j
vnoremap <C-h> h
vnoremap <C-l> l

" Function keys
nnoremap <f7> :set fileencoding? fileformat? filetype?<enter>
nnoremap <f8> :setlocal rnu! nu!<enter>

set spellcapcheck=
set spellsuggest=best,13
nnoremap <f9> :setlocal spell! spelllang=pl_pl,en_us,de<enter>
nnoremap [s [szz
nnoremap ]s ]szz
nnoremap z= zzz=

set listchars=space:·,trail:•,eol:¶
nnoremap <f10> :setlocal list!<enter>

" Leader
let mapleader = " "

nnoremap <leader>sl :set tw=99999<cr>
nnoremap <leader>ss :set tw=74<cr>
nnoremap <leader>sf :set fo=tawc<cr>
nnoremap <leader>sc :set fo=croql<cr>
nnoremap <leader>sF :set fo=cql<cr>
nnoremap <leader>st :set filetype=

nnoremap <silent> <leader>me G{}k$zz
nnoremap <leader>mh ?^

nnoremap <silent> <leader>tt :tabnew<CR>
nnoremap <silent> <leader>n :tabnext<cr>
nnoremap <silent> <leader>p :tabprev<cr>
nnoremap <silent> <leader>tn :tabm +1<CR>
nnoremap <silent> <leader>tp :tabm -1<CR>
nnoremap <silent> <leader>tw :tabclose<CR>
nnoremap <silent> <leader>tz :tabnew<CR>:terminal<CR>

nnoremap <silent> <CR> :noh<CR>
nnoremap <silent> <leader>q :noh<CR>
nnoremap <silent> <leader>h :noh<CR>

nnoremap <silent> <leader>ab viwc****<Esc>hPe
nnoremap <silent> <leader>ai viwc**<Esc>Pe
nnoremap <silent> <leader>au viwc__<Esc>Pe
nnoremap <silent> <leader>as 43o<esc>43k$zz
nnoremap <silent> <leader>aa 11o<esc>11k$zz

vnoremap <silent> <leader>ab c****<Esc>hPe
vnoremap <silent> <leader>ai c**<Esc>Pe
vnoremap <silent> <leader>au c__<Esc>Pe

nnoremap <leader>ee :e ~/**/*
nnoremap <leader>en :e ~/Dokumenty/Notatki/**/*
nnoremap <leader>es :e ~/1-STUDIA/**/*
nnoremap <leader>ec :e ~/.config/**/*
nnoremap <leader>ev :e ~/vimwiki/**/*

nnoremap <leader>b :b <C-d>

" Save location
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | execute "normal! g`\"" | endif
endif

" Vimwiki
let g:vimwiki_global_ext = 0
" :verb set fo
" vim ~/path
" set fo=tawc nosmartindent autoindent 

